name: Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.31.0'

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.0.4

      - name: Install required libraries
        run: |
            arduino-cli lib update-index
            arduino-cli lib install "AsyncTCP@1.1.4"
            arduino-cli lib install "ESPAsyncWebServer@3.0.6"
            arduino-cli lib install "LiquidCrystal@1.0.7"
            arduino-cli lib install "OneWire@2.3.8"
            arduino-cli lib install "DallasTemperature@3.9.0"

      - name: Compile
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 ESP32/ESP32.ino
